mysite/moodle/urls.py
# myapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views
from .views import SignUpView
from django.contrib.auth import views as auth_views


# app_name = "moodle"

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),

    path('activate/<slug:uidb64>/<slug:token>/',views.activate, name='activate'),

    path('about_us/',views.aboutview, name='aboutus'),
    path('register/',views.register, name='signupnew'),
    path('user/',views.userpage,name="userpage"),
    path('editprofile/',views.editprofile,name="editprofile"),
    # path('change_password/', views.change_password, name='change_password'),
    path('student/',views.studentpage,name="studentpage"),
    path('teacher/',views.teacherpage,name="teacherpage"),
    path('ta/',views.tapage,name="tapage"),

    path('student/calendar/', views.CalendarView.as_view(), name='calendar'),
    path('teacher/calendar/', views.CalendarView.as_view(), name='calendar'),
    path('ta/calendar/',views.CalendarView.as_view(), name='calendar'),

    path('student/<str:uid>/',views.studentcoursepage,name="studentcoursepage"),
    path('teacher/<str:uid>/',views.teachercoursepage,name="teachercoursepage"),
    path('ta/<str:uid>/',views.tacoursepage,name="tacoursepage"),

    path('uplda/<str:uid>/',views.uploada,name="uploadapage"),
    path('upldb/<str:uid>/<str:aid>/',views.uploadb,name="uploadbpage"),
    path('upldv/<str:code>/',views.uploadv,name="uploadvpage"),
    path('upldl/<str:uid>/',views.uploadl,name="uploadlpage"),
    path('uplag/<str:uid>/<str:aid>/', views.uploadag, name="uploadagpage"),
    path('autograde/<str:uid>/<str:aid>/', views.autograde, name="autogradepage"),

    path('dnlda/<str:code>/',views.downloada,name="downloadapage"),
    path('dnldb/<str:code>/<str:title1>/',views.downloadb,name="downloadbpage"),

    path('grading/<str:code>/<str:title1>', views.uploadg,name="uploadgpage"),

    path('tapriviledge/<str:code>/', views.tapriviledge, name="tapriviledgepage"),

    path('createcourse/',views.createcoursepage,name="createcoursepage"),
    path('addstudent/',views.addstudentpage,name="addstudentpage"),

    
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),

    path('statistics/',views.graphpage,name='statisticspage'),
    path('statistics/<str:uid>/',views.graphcoursepage,name='statistics_course_page'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

from moodle.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mysite/', include('moodle.urls')), #newly added
    path('mysite/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # newly added

    # path('chat/', index, name='index'),
    path('chat/<str:room_name>/', room, name='room'),
    path('chat/<str:room_name>/on_off', on_off, name='on_off'),


    path('privatechat/', privatechat, name='privatechat'),
    path('privatechat/<str:room_name>/', privateroom, name='privateroom'),

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/moodle/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
from  embed_video.fields  import  EmbedVideoField


# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	course_list = models.JSONField(default=dict)

	def __str__(self):
		return self.user.username

	@receiver(post_save, sender=User) 
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Profile.objects.create(user=instance)

	@receiver(post_save, sender=User)
	def save_user_profile(sender, instance, **kwargs):
		instance.profile.save()
	


class Course(models.Model):
	course = models.ForeignKey(Profile, on_delete = models.CASCADE)
	course_code = models.CharField(max_length=100, default='')
	user_list = models.JSONField(default=dict)
	user_names = models.CharField(max_length=100000,default='',blank=True)
	roles = models.CharField(max_length=100000,default='',blank=True)
	chat_status = models.BooleanField(default=True)
	def __str__(self):
		return self.course_code


class Uploada(models.Model):
	title = models.CharField(max_length=100, default='')
	course_code = models.CharField(max_length=100, default='')
	uploada = models.FileField(upload_to="media/uploada")
	description = models.TextField(default='')
	weightage = models.IntegerField(default='100')
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()
	is_ag = models.IntegerField(default=0)

	def __str__(self):
		return self.title + "/" + str(self.course_code)

class Uploadb(models.Model):
	by_whom = models.CharField(max_length=100,default='')
	title = models.CharField(max_length=100, default='')
	uploadb = models.FileField(upload_to="media/uploadb")
	course_code = models.CharField(max_length=100, default='')
	status = models.IntegerField(default='0')
	solution_for = models.CharField(max_length=100, default='')
	submit_time = models.DateTimeField()
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()
	weightage = models.IntegerField(default='100')
	grade_status = models.IntegerField(default='0')
	grade = models.IntegerField(default='0')
	feedback = models.TextField(default='')

	def __str__(self):
		return self.title + "/" + str(self.course_code)

class Uploadg(models.Model):
	course_code = models.CharField(max_length=100, default='')
	title = models.CharField(max_length=100, default='')
	uploadg = models.FileField(upload_to="media/uploadg")

	def __str__(self):
		return self.title + "/" + str(self.course_code)

class Grading(models.Model):
	course_code = models.CharField(max_length=100, default='')
	assignment_name = models.CharField(max_length=100, default='')
	mark_list = models.JSONField(default=dict)

	def __str__(self):
		return self.course_code + "/" + str(self.assignment_name)

class Uploadl(models.Model):
	title = models.CharField(max_length=100, default='')
	course_code = models.CharField(max_length=100, default='')
	uploadl = models.FileField(upload_to="media/uploadl")
	description = models.TextField(default='', blank=True)

	def __str__(self):
		return self.title + "/" + str(self.course_code)

class Uploadv(models.Model):
	title = models.CharField(max_length=100, default="")
	course_code = models.CharField(max_length=100, default="")
	description = models.TextField(default="")
	video_url = EmbedVideoField()
	submit_time = models.DateTimeField()

	def __str__(self):
		return self.title + "/" + str(self.course_code) + "/video" 

class tapriviledges(models.Model):
	# CHOICES = (
	# 	('1','Enroll new students to a course'),
	# 	('2','Add new Assignments'),
	# 	('3','Upload marks and feedback.'),
	# )
	ta_name = models.CharField(max_length=100,default='')
	course_code = models.CharField(max_length=100,default='') 
	enrollment = models.BooleanField(default=False)
	add_assignment = models.BooleanField(default=False)
	grade_assignment = models.BooleanField(default=True)

	def __str__(self):
		return self.ta_name + "/" + str(self.course_code)

# from django.contrib.auth import get_user_model
# User = get_user_model()

class Message(models.Model):
    author = models.ForeignKey(User, related_name='author_messages', on_delete=models.CASCADE)
    room_name = models.CharField(max_length=100, default='')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.room_name

    def last_10_messages(room):
    	return Message.objects.order_by('-timestamp').filter(room_name=room)[:10]


class PrivateChat(models.Model):
	username = models.CharField(max_length=100, default='')


class Uploadag(models.Model):
    course_code = models.CharField(max_length=100, default='')
    uploadag = models.FileField(upload_to="media/uploadag")
    ag_for = models.CharField(max_length=100, default='')
    def __str__(self):
        return str(ag_for) + "/" + str(self.course_code) + "/" + str(ag)

mysite/moodle/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.forms import ModelForm, DateInput

class RegistrationForm(UserCreationForm):
	first_name = forms.CharField(max_length=50,required=True)
	
	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2',	
		)



class UserForm(forms.ModelForm):
	first_name = forms.CharField(max_length=50,required=True)
	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			)


class CourseForm(forms.ModelForm):
	class Meta:
		model = Course
		fields = (
			'course_code',
			)

class UploadaForm(forms.ModelForm):
	title = forms.CharField(max_length=50,required=True)
	uploada = forms.FileField()
	class Meta:
		model = Uploada
		widgets = {
			'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
			'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
	    }
		fields = (
			'title',
			'description',
			'uploada',
			'weightage',
			'start_time',
			'end_time',
			)
	def __init__(self, *args, **kwargs):
		super(UploadaForm, self).__init__(*args, **kwargs)
		# input_formats parses HTML5 datetime-local input to datetime field
		self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
		self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)


class UploadlForm(forms.ModelForm):
	title = forms.CharField(max_length=50,required=True)
	uploadl = forms.FileField()
	class Meta:
		model = Uploadl
		fields = (
			'title',
			'description',
			'uploadl',
			)
		
class UploadgForm(forms.ModelForm):
	uploadg = forms.FileField()
	class Meta:
		model = Uploadg
		fields = (
			'uploadg',
			)

class UploadagForm(forms.ModelForm):
	uploadag = forms.FileField()
	class Meta:
		model = Uploadag
		fields = (
			'uploadag',
			)


class UploadbForm(forms.ModelForm):
	uploadb = forms.FileField()
	class Meta:
		model = Uploadb
		fields = (
			'uploadb',
			)

class UploadvForm(forms.ModelForm):
	class Meta:
		model = Uploadv
		fields = (
			'title',
			'description',
			'video_url',
			)

class StudentForm(forms.ModelForm):
	class Meta:
		model = Course
		fields = (
			'course_code',
			'user_names',
			'roles',
			)

def save(self, commit=True):
	user = super(RegistrationForm, self).save(commit=False) 	
	user.first_name = self.cleaned_data['first_name']
	user.last_name = self.cleaned_data['last_name']
	user.email = self.cleaned_data['email']

class TAForm(forms.ModelForm):
	ta_name = models.CharField(max_length=100,default='')
	class Meta:
		model = tapriviledges
		fields = (
			'ta_name',
			# 'course_code',
			'enrollment',
			'add_assignment',
			'grade_assignment',
			)

class PrivateChatForm(forms.ModelForm):
	class Meta:
		model = PrivateChat
		fields = (
			'username',
			)

mysite/moodle/templates/about.html
{% extends 'base.html' %}

{% block title %}About Us {% endblock %}

{% block content %}

<section style="background-image: linear-gradient(#460985,#4ef5f2)";>
<section>
  <br>
  <div class="image_hat" style="float:right; margin-right:30px ; opacity: 0.7;">
  <img class="image_img" src="https://drive.google.com/uc?export=view&id=1yxBzhtwb5gUCQ8JcdyK3_1PoX1UNmRnI" alt="HowUDoing">
  </div>
  <h1 style="color:#e1eff7"><big>Heyy! Whats Up'😉</big></h1>
  <h1 style="color:#dfff2b; font: fantasy;" ><big>WELCOME Ladies-n-Gentlemen to our AboutUs page!!</big></h1>
  <hr>
</section>

<div>
  <div style="float: left;margin-right:20px ;">
  <img src="https://drive.google.com/uc?export=view&id=1vHl-eJPw9ZI_CHmFk8rFtr_X_CuFi1BR" alt="Anubhab" width="270" height="300" />
  <span title="Hello friend, so how are u today !! Say hello to my friend Praneeth 👀!"><p>Anubhab Ray</p></span>
  </div>

  <div style="float: left;margin-right:50px ;">
  <img src="https://drive.google.com/uc?export=view&id=1EQcQ-8M6i9BhTVdrO87e7FCGKMVnwf05" alt="Praneeth" width="270" height="300" />
  <span title="Hello there !! So u are enjoing this hover over bussiness, Good 👐!!"><p>Mani Praneeth </p></span>
  </div>
</div>


<section >
  <h2 style="color:#ffffff">This website is created by Anubhab and Praneeth</h2>
  <h4 style="color: #cdb8fc;text-align: left;"> Wanted to say so many things here that make us who we are, but nobody is gonna read that anyway. <br> So hitting straight, just for fun ,on the left hand hover over the names under our pictures !! <br>There are aslo very beautiful hover-over-my-picture elements at the bottom of this page. 
  <i>Hope u like them.</i> 
 
  </h4>
  <p style="text-align: left;">Anubhab Ray - 200050010<br>IIT Bombay, BTech CSE<br></p>
  <p style="text-align: left;">Chilukuri Mani Praneeth - 200050028<br>IIT Bombay, BTech CSE<br></p>
  <a href="{% url 'home' %}"> <button class="button button1">Back to Home </button></a>
</section>

</section>


<hr size="10" color="#4ef5f2">
<section >
  <p style="margin-bottom:2cm; margin-left: 0; margin-top: 0;">
    <div class="myDIV"> Wanna follow us 💛 Then do checkout our insta and fb pages. </div>
    <div class="hide"><i>Basically asking for personal promotion is unprofessional but again who is judging !!</i></div>  

    <hr width="50%" size="5" color="#e3d1ff">
    <br> Anubhab : 
    <a href="https://www.instagram.com/jackiejack204/"> <i class="fab fa-instagram fa-lg"></i></a> 
    & <a href="https://www.facebook.com/anubhab.ray.5209"> <i class="fab fa-facebook-f fa-1.25x" style="color:blue;"> </i></a> 

    <hr width="15%" size="5" color="#e3d1ff">
    <br>Praneeth : 
    <a href="https://www.instagram.com/praneeth__7781/"><i class="fab fa-instagram fa-lg"></i></a>
    &  <a href="https://www.facebook.com/manipraneeth2307"> <i class="fab fa-facebook-f fa-1.25x" style="color:blue;"> </i></a> 
  </p>
</section>
<br>


<section>

<div class="image_anubhab" style="float: left;margin-left:60px ;">
  <img class="image_img" src="https://drive.google.com/uc?export=view&id=11D_8XxwzlrS_jgU4Eu4F7J0WjefFt0Pa" alt="Anubhab's">
  <div class="image_overlay image_overlay_blur">
    <div class="image_title">Hello <big>👐</big></div>
    <p class="image_description">My hobbies:Painting, Book Reading<br>interests:Tinkering with devices </p>
  </div>
</div>


<div class="image_anubhab" style="float: left;margin-left:120px ;">
  <img class="image_img" src="https://drive.google.com/uc?export=view&id=1vxeu5E6wOAddiNDBLiEA_oJqLxNX9FeZ" alt="Anubhab's">
  <div class="image_overlay image_overlay_blur">
    <div class="image_title">BYE...GOOD BYE<big>👐</big></div>
    <p class="image_description">Do visit Us Again <br> We will be waiting for U <big>😇</big></p>
  </div>
</div>


<div class="image_praneeth" style="float: right;margin-right:60px ;">
  <img class="image_img" src="https://drive.google.com/uc?export=view&id=1aVReiuTt485I4o2laom7kUaw65_LW9oj" alt="Praneeth's">
  <div class="image_overlay image_overlay_blur">
    <div class="image_title"> Hello <big>👐</big> </div>
    <p class="image_description"> My hobbies:Reading and Writing Novels<br>Interests:Cricket, Literature, Music</p>
</div>

</section>


{% endblock %}

mysite/moodle/templates/uploada.html
{% extends 'base.html' %}
{% block title %}UploadA{% endblock %}
{% block content %}


<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom" style="background-color: teal; position: sticky; top:0;">
  <a href="\" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" style="pointer-events: none;">
  <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentcolor" style="color: white; margin-left: 0.5rem;" class="bi bi-heart-fill" viewBox="0 0 16 16">
   <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
  </svg>
  <span class="fs-4" style="color: white; margin-left: 1rem;"><b>MOODLE ~ LITE</b><br><strong style="font-size: 20px; color:beige;">Learning Made Easier</strong></span>
  </a>
  <ul class="nav flex-column">
    <li class="nav-item">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a href="{% url 'home' %}" class="nav-link button1" style="color: white;" aria-current="page">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house-door-fill" style="color: white; margin-left: 0.5rem; margin-right: 0.5rem;" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
            </svg>
          HOME
          </a>
        </li>
        <li class="nav-item"><a href="{% url 'userpage' %}" class="nav-link button1" style="color: white;">My Profile</a></li>
        <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link button1" style="color: white;">Log Out</a></li><br>
      </ul>
    </li>
    <li class="nav-item"><a id="mytime" style="color: white; text-align: right; margin-left: 6.8rem;"></a></li>
  </ul>
</header>

{% if user.is_authenticated %} 


<h1> This is the Upload Assignment Section | <img id="icon" src="../../../static/images/moon.png" alt="moon.png" /> </h1>


 <form method="POST" enctype="multipart/form-data">
	{% csrf_token%}

<!-- 	<label for="id_title" class="form-label">Title</label> 
    <input type="text" class="form-control" name="title" autofocus="" autocapitalize="none" autocomplete="title" maxlength="150" required="" id="id_title" placeholder="myfile.txt/pdf" aria-describedby="TitleHelp">
    <div id="TitleHelp" class="form-text"></div>


    <label for="id_nature" class="form-label">file nature</label> 
    <input type="text" class="form-control" name="file_nature" autofocus="" autocapitalize="none" autocomplete="filenature" maxlength="150" required="" id="id_nature" placeholder="hxjhasx" aria-describedby="TitleHelp">
    <div id="TitleHelp" class="form-text"></div>
	

	
	<input type="file" name="upload" class="form-control" id="formFile">
	

	<p><label for="id_course_code">Course code:</label> <input type="text" name="course_code" maxlength="100" required="" id="id_course_code"></p> -->



	{{ form.as_p }}

<!-- 
	<p><label for="id_title">Title:</label> <input type="text" name="title" maxlength="50" required="" id="id_title"></p>
	<p><label for="id_upload">Upload:</label> <input type="file" name="upload" required="" id="id_upload"></p>
	
	<p><label for="id_file_nature">File nature:</label> <input type="text" name="file_nature" maxlength="100" required="" id="id_file_nature"></p> -->




	<button class="button button1" type="submit" value="SAVE"> Upload </button>

	
   
</form>

  {% else %}
    <section>
        <br>
        <h1 > NOT AUTHENTICATED USER !!</h1>
        <hr>
    </section>

    {% endif %}


{% endblock %} 

mysite/moodle/templates/uploadb.html
{% extends 'base.html' %}
{% block title %}UploadB{% endblock %}
{% block content %}


<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom" style="background-color: teal; position: sticky; top:0;">
  <a href="\" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" style="pointer-events: none;">
  <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentcolor" style="color: white; margin-left: 0.5rem;" class="bi bi-heart-fill" viewBox="0 0 16 16">
   <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
  </svg>
  <span class="fs-4" style="color: white; margin-left: 1rem;"><b>MOODLE ~ LITE</b><br><strong style="font-size: 20px; color:beige;">Learning Made Easier</strong></span>
  </a>
  <ul class="nav flex-column">
    <li class="nav-item">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a href="{% url 'home' %}" class="nav-link button1" style="color: white;" aria-current="page">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house-door-fill" style="color: white; margin-left: 0.5rem; margin-right: 0.5rem;" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
            </svg>
          HOME
          </a>
        </li>
        <li class="nav-item"><a href="{% url 'userpage' %}" class="nav-link button1" style="color: white;">My Profile</a></li>
        <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link button1" style="color: white;">Log Out</a></li><br>
      </ul>
    </li>
    <li class="nav-item"><a id="mytime" style="color: white; text-align: right; margin-left: 6.8rem;"></a></li>
  </ul>
</header>


{% if user.is_authenticated %} 


<h1> This is the Upload Solution Section | <img id="icon" src="../../../static/images/moon.png" alt="moon.png" /></h1>


 <form method="POST" enctype="multipart/form-data">
	{% csrf_token%}

<!-- 	<label for="id_title" class="form-label">Title</label> 
    <input type="text" class="form-control" name="title" autofocus="" autocapitalize="none" autocomplete="title" maxlength="150" required="" id="id_title" placeholder="myfile.txt/pdf" aria-describedby="TitleHelp">
    <div id="TitleHelp" class="form-text"></div>


    <label for="id_nature" class="form-label">file nature</label> 
    <input type="text" class="form-control" name="file_nature" autofocus="" autocapitalize="none" autocomplete="filenature" maxlength="150" required="" id="id_nature" placeholder="hxjhasx" aria-describedby="TitleHelp">
    <div id="TitleHelp" class="form-text"></div>
	

	
	<input type="file" name="upload" class="form-control" id="formFile">
	

	<p><label for="id_course_code">Course code:</label> <input type="text" name="course_code" maxlength="100" required="" id="id_course_code"></p> -->



	{{ form.as_p }}

<!-- 
	<p><label for="id_title">Title:</label> <input type="text" name="title" maxlength="50" required="" id="id_title"></p>
	<p><label for="id_upload">Upload:</label> <input type="file" name="upload" required="" id="id_upload"></p>
	
	<p><label for="id_file_nature">File nature:</label> <input type="text" name="file_nature" maxlength="100" required="" id="id_file_nature"></p> -->




	<button class="button button1" type="submit" value="SAVE"> Upload </button>

	
   
</form>

  {% else %}
    <section>
        <br>
        <h1 > NOT AUTHENTICATED USER !!</h1>
        <hr>
    </section>

    {% endif %}


{% endblock %} 